<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 7/30/2016
 * Time: 12:30 PM
 */

namespace backend\modules\api\controllers;


use backend\models\Health;
use yii\rest\ActiveController;

class HealthController extends ActiveController
{

    public function init()
    {
        $this->modelClass = Health::className();
        parent::init(); // TODO: Change the autogenerated stub
    }



}