<?php

namespace common\modules\content\controllers;

use backend\controllers\CRUDController;
use common\models\Menu;
use common\models\search\MenuSearch;
use common\modules\i18n\Module;

/**
 * MenusController implements the CRUD actions for Menu model.
 */
class MenusController extends CRUDController
{

    /**
     * Initialize function
     */
    public function init()
    {
        $this->beanClass = Menu::className();
        $this->beanSearchClass = MenuSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Sort and position action for menu
     * @return string
     */
    public function actionSort()
    {
        if (\Yii::$app->request->post()) {
            $jsonTree = \Yii::$app->request->post('jsonTree');
            if (!empty($jsonTree)) {
                $beanClass = $this->beanClass;
                $beanClass::saveMenuTree($jsonTree);
                \Yii::$app->session->setFlash('success', Module::t('Operation is done successfully.'));
                return $this->redirect(['sort']);
            }
        }
        return $this->render('sort');
    }

}
