<?php

namespace common\modules\content\controllers;

use backend\controllers\CRUDController;
use common\models\Post;
use common\models\search\PostSearch;

/**
 * PostsController implements the CRUD actions for Post model.
 */
class PostsController extends CRUDController
{
    public function init()
    {
        $this->beanClass = Post::className();
        $this->beanSearchClass = PostSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }

}
