<?php

namespace backend\modules\settings\controllers;

use backend\controllers\AuthController;
use backend\controllers\CRUDController;
use developeruz\db_rbac\behaviors\AccessBehavior;
use Yii;
use backend\models\Brand;
use backend\models\search\BrandSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BrandsController implements the CRUD actions for Brand model.
 */
class BrandsController extends CRUDController
{

    public function init()
    {
        $this->beanClass = Brand::className();
        $this->beanSearchClass = BrandSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }
}
