<?php

namespace backend\modules\settings\controllers;

use backend\controllers\CRUDController;
use backend\models\ContactFormSetting;
use backend\models\search\ContactFormSettingSearch;

/**
 * ContactFormSettingsController implements the CRUD actions for ContactFormSetting model.
 */
class ContactFormSettingsController extends CRUDController
{
    /**
     * Init bean class
     */
    public function init()
    {
        $this->beanClass = ContactFormSetting::className();
        $this->beanSearchClass = ContactFormSettingSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }
}
