<?php

namespace backend\modules\settings\controllers;

use backend\controllers\AuthController;
use backend\controllers\CRUDController;
use developeruz\db_rbac\behaviors\AccessBehavior;
use Yii;
use backend\models\Template;
use backend\models\search\TemplateSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TemplatesController implements the CRUD actions for Template model.
 */
class TemplatesController extends CRUDController
{

    public function init()
    {
        $this->beanClass = Template::className();
        $this->beanSearchClass = TemplateSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Creates a new Template model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $extraParams = [
            'templates' =>  Template::getTemplateChunks()
        ];
        return parent::actionCreate($extraParams);
    }

    /**
     * Updates an existing Template model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $extraParams = [
            'templates' =>  Template::getTemplateChunks()
        ];
        return parent::actionUpdate($id, false, $extraParams);
    }
}
