<?php
/**
 * Created by PhpStorm.
 * User: artem
 * Date: 6/6/16
 * Time: 11:17 AM
 */

namespace backend\widgets;


use yii\base\Widget;

/**
 * Widget for form buttons like 'Update','Create','Back to list'
 * @author Artem Kramov
 */
class FormButtons extends Widget
{
    /**
     * Model object
     * @var object $model
     */
    public $model;

    /**
     * Type of the form button
     * @var string $type
     */
    public $type = "view";

    /**
     * Singular name of the model
     * @var string $modelLabel
     */
    public $modelLabel = "";

    /**
     * Path to widget view
     * @var string
     */
    private $viewPath;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->viewPath = "form_buttons" . DIRECTORY_SEPARATOR . $this->type;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render($this->viewPath, [
            'model'      => $this->model,
            'modelLabel' => $this->modelLabel
        ]);
    }

}