<?php

namespace frontend\widgets;

use backend\models\SocialLink;

/**
 * Class SocialLinkWidget
 * @package frontend\widgets
 * Widget for displaying of the social links
 */
class SocialLinkWidget extends \yii\base\Widget
{
    /**
     * @var string
     */
    private $viewName;

    /**
     * Init view path
     */
    public function init()
    {
        $this->viewName = 'social-link' . DIRECTORY_SEPARATOR . 'view';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function run()
    {
        $socialLinks = SocialLink::find()->orderBy('sort')->all();
        return $this->render($this->viewName, [
            'links' => $socialLinks
        ]);
    }

}