<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 8/1/2016
 * Time: 1:51 PM
 */

namespace frontend\web\themes\diploma;


use yii\web\AssetBundle;

class FrontendAsset extends AssetBundle
{

    public $sourcePath = "@frontend/web/themes/diploma/dist/";

    public $css = [
        'css/normalize.css',
        'css/font-awesome.min.css',
        'css/owl.carousel.css',
        'css/owl.theme.css',
        'css/icheck/all.css',
        'css/jquery.fancybox.css',
        'css/widget.css',
        'css/swiper.min.css',
        'http://vjs.zencdn.net/5.10.8/video-js.css',
        'css/magnify.css',
        'css/jquery-ui.css',
        'css/Scrollbar.min.css',
        'css/woocommerce-layout.css',
        'css/woocommerce-smallscreen.css',

        'css/woocommerce.css',
        'css/js_composer.css',
        'css/site.css',
        'css/flags.css',
    ];

    public $js = [
        //'js/front.js',
        'js/js_composer_front.js',
        'js/lib/jquery.zoom.min.js',
        'js/lib/owl.carousel.min.js',
        'js/lib/swiper.jquery.min.js',
        'js/lib/jquery.zoom.min.js',
        'js/lib/history.js',
        'js/lib/jquery.mask.js',
        'js/lib/URI.min.js',
        'js/lib/turn.min.js',
        'js/lib/hash.js',
        'js/lib/jquery-ui-components.min.js',

        'js/lib/jquery.fancybox.js',
        'http://vjs.zencdn.net/5.10.8/video.js',
        'js/lib/icheck.min.js',
        'js/scripts.js',
        'js/App.js',
        'js/Footer.js',
        'js/ContactForm.js',
        'js/ProductFilter.js',
        'js/Product.js',
        'js/Basket.js',
        'js/Checkout.js',
        'js/Search.js',
        'js/Menu.js',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->publishOptions['forceCopy'] = true;
    }

    public $depends = [
        'yii\web\YiiAsset',
    ];


}